Added order status management endpoints in the FastAPI application. I…
AHL-Logics-backend-tranining-2024/Final-Project---Team-4 pull request #6
Opened 2024-10-16 20:36 UTC by sajalahalih

…mplemented CRUD operations for managing order statuses, including:

- `POST /statuses/` to create a new status with validation for unique names.
- `GET /statuses/{status_id}` to retrieve details of a specific status by its ID.
- `PUT /statuses/{status_id}` to update an existing status name with uniqueness validation.
- `DELETE /statuses/{status_id}` to remove a status, ensuring it is not in use by any orders.

Enhanced code documentation with detailed comments for clarity and maintainability.

2024-10-16 20:36 UTC, FatmaQunnies24 approved these changes

2024-10-17 06:02 UTC, Mohammed-samaheen requested changes
Just a small change; overall, nice job!

2024-10-17 06:02 UTC, Mohammed-samaheen commented on app/__pycache__/__init__.cpython-312.pyc
Please remove all the` __pycache__ `files from this PR.

2024-10-17 06:02 UTC, Mohammed-samaheen commented on app/api/routes/OrderStatus.py
Please use snake_case for file naming.

2024-10-17 06:02 UTC, Mohammed-samaheen commented on app/api/routes/OrderStatus.py
> +    await new_status.save()
Did you test your changes? I couldn't find this syntax in the SQLModel documentation. Here's an [example](https://sqlmodel.tiangolo.com/tutorial/insert/#create-a-model-instance) of how it's done.

2024-10-17 06:02 UTC, Mohammed-samaheen commented on app/api/routes/OrderStatus.py
> +    await new_status.save()
If such syntax exists, please send me a link

2024-10-22 19:53 UTC, closed without merging