database for order and order statues done & fix errors
AHL-Logics-backend-tranining-2024/Final-Project---Team-4 pull request #9
Opened 2024-10-22 19:08 UTC by sajalahalih

2024-10-22 19:15 UTC, ayanourr approved these changes

2024-10-22 19:44 UTC, ayanourr commented on app/schemas/order_status_schema.py
> +        orm_mode = True
add( from_attributes=True ) to the config

2024-10-23 05:32 UTC, Mohammed-samaheen requested changes

2024-10-23 05:32 UTC, Mohammed-samaheen commented on app/api/routes/order_status.py
> +    async with Session(engine) as session:
Please follow the same convention across the entire repo. You were using `session: Session = Depends(get_session)`, so continue using it consistently.

2024-10-23 05:32 UTC, Mohammed-samaheen commented on app/api/routes/order_status.py
> +    return
No need for this line

2024-10-23 05:32 UTC, Mohammed-samaheen commented on app/schemas/order_schema.py
> +    products: List[dict]
List[OrderProduct]

2024-10-23 05:32 UTC, Mohammed-samaheen commented on app/schemas/order_status_schema.py
> +    updated_at: datetime
this can be null

2024-10-23 05:32 UTC, Mohammed-samaheen commented on app/services/order_service.py
> +            order_products_data.append(OrderProduct(product_id=product.id, quantity=item.quantity))
You haven't deducted the product stock based on the order product quantity.

2024-10-23 05:32 UTC, Mohammed-samaheen commented on app/services/order_service.py
> +        for op in order_products_data:
Just to let you know, we can add order products directly. Check this [example](https://sqlmodel.tiangolo.com/tutorial/relationship-attributes/create-and-update-relationships/#create-a-team-with-heroes) **[no need to update the code].**

2024-10-23 16:18 UTC, Mohammed-samaheen approved these changes

2024-10-23 16:20 UTC, merged